### ISSUE TITLE
Rewrite

### ISSUE THREAD

**Issue by jw1912** [jw1912/bullet#139]
[Rewrite branch](https://github.com/jw1912/bullet/tree/rewrite)

### Description
- Take advantage of the autograd crate I wrote ([diffable](https://github.com/jw1912/diffable))
- Generally massively improve confidence in the safety of code
- Unify HIP and CUDA backends
- Retire CPU backend (ono)

### Why this would be useful?
- Autograd is cool and makes adding new features much easier
- Single unified HIP/CUDA backend means only one needs to be maintained

### TODO-List
- [x] Remove CPU backend
- [x] Unify HIP and CUDA backends
  - [x] Windows-CUDA working
  - [x] Windows-HIP working
  - [x] Linux-CUDA working
  - [x] Linux-HIP working
- [x] Rewrite `Tensor` class
  - [x] `DenseMatrix` variant
  - [x] `SparseMatrix` variant
- [x] Reimplement all tensor operations
- [x] Write tests for all tensor operations
- [x] Reimplement training code
  - [x] Core training function
  - [x] Improve various parts of the training code
- [x] Reimplement `TrainerBuilder`
- [x] Get examples working exactly as before
